-- 0001 core schema: identifiers, closed vocabularies, vacancy, immutable requirement sets.
-- Plan refs: INTG-01 (stable IDs), JOB-01, JOB-04, JOB-07 (versioned, frozen criteria), §13.5.

-- INTG-01: stable, sortable, non-sequential ULIDs generated by the application.
-- The domain makes a malformed identifier impossible to persist.
CREATE DOMAIN ulid AS CHAR(26)
  CHECK (VALUE ~ '^[0-9A-HJKMNP-TV-Z]{26}$');

-- Closed vocabularies. These mirror packages/shared/src/taxonomy.ts; a CI script asserts parity.
CREATE TYPE requirement_class AS ENUM ('mandatory', 'preferred', 'informational', 'disqualifier');
CREATE TYPE confidence_level  AS ENUM ('high', 'medium', 'low', 'unknown');
CREATE TYPE screening_profile AS ENUM ('volume', 'depth');
CREATE TYPE actor_kind        AS ENUM ('human', 'service');

-- Tenancy boundary established now so a future service-line option (decision 21) stays open.
CREATE TABLE organization (
  id         ulid PRIMARY KEY,
  name       TEXT NOT NULL CHECK (length(btrim(name)) > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- JOB-01
CREATE TABLE vacancy (
  id            ulid PRIMARY KEY,
  org_id        ulid NOT NULL REFERENCES organization(id),
  title         TEXT NOT NULL CHECK (length(btrim(title)) > 0),
  department    TEXT,
  location      TEXT,
  employment_type TEXT,
  -- D6 / JOB-11: chosen at creation, governed afterwards. NULL until selected (R1b).
  profile       screening_profile,
  -- INTG-01: optional slot for the eventual Oracle HCM requisition key (R4).
  external_ref  TEXT,
  created_by    ulid NOT NULL,           -- named principal (IAM-05); FK to user lands with IAM-03
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX vacancy_org_idx ON vacancy (org_id, created_at DESC);
CREATE UNIQUE INDEX vacancy_external_ref_uq ON vacancy (org_id, external_ref) WHERE external_ref IS NOT NULL;

CREATE TABLE job_description_version (
  id          ulid PRIMARY KEY,
  vacancy_id  ulid NOT NULL REFERENCES vacancy(id),
  version     INT  NOT NULL CHECK (version > 0),
  body        TEXT NOT NULL,
  source_kind TEXT NOT NULL CHECK (source_kind IN ('pasted', 'uploaded')),
  created_by  ulid NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (vacancy_id, version)
);

-- JOB-07: versioned; frozen when a screening run starts. Frozen sets are immutable (trigger below).
CREATE TABLE requirement_set (
  id            ulid PRIMARY KEY,
  vacancy_id    ulid NOT NULL REFERENCES vacancy(id),
  version       INT  NOT NULL CHECK (version > 0),
  jd_version_id ulid NOT NULL REFERENCES job_description_version(id),
  created_by    ulid NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  frozen_at     TIMESTAMPTZ,            -- NULL = still editable
  UNIQUE (vacancy_id, version)
);

CREATE TABLE requirement (
  id                 ulid PRIMARY KEY,
  requirement_set_id ulid NOT NULL REFERENCES requirement_set(id),
  text               TEXT NOT NULL CHECK (length(btrim(text)) > 0),
  classification     requirement_class NOT NULL,
  weight             NUMERIC(5,2) CHECK (weight IS NULL OR (weight >= 0 AND weight <= 100)),
  extraction_conf    confidence_level,    -- drives the JOB-05 uncertainty flag
  -- Provenance back to the JD span. FK to evidence_span is added in the PARSE migration (S8);
  -- until then the column holds NULL.
  source_span_id     ulid,
  -- §13.5: disqualifiers are rules, not preferences, and never carry a weight (KNOCK epic).
  CONSTRAINT disqualifier_has_no_weight CHECK (classification <> 'disqualifier' OR weight IS NULL)
);
CREATE INDEX requirement_set_idx ON requirement (requirement_set_id);

-- JOB-07 / AC-10: a completed run must always resolve to the exact criteria it used.
-- Enforced in the database, not only in application code, so no code path can retro-edit results.
CREATE FUNCTION forbid_change_when_frozen() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  set_id ulid;
  frozen TIMESTAMPTZ;
BEGIN
  IF TG_TABLE_NAME = 'requirement_set' THEN
    IF TG_OP = 'DELETE' THEN
      IF OLD.frozen_at IS NOT NULL THEN
        RAISE EXCEPTION 'requirement_set % is frozen and cannot be deleted', OLD.id USING ERRCODE = '55000';
      END IF;
      RETURN OLD;
    END IF;
    -- UPDATE: a frozen set may not change at all (including un-freezing it).
    IF OLD.frozen_at IS NOT NULL THEN
      RAISE EXCEPTION 'requirement_set % is frozen and cannot be modified', OLD.id USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
  END IF;

  -- requirement rows
  set_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.requirement_set_id ELSE NEW.requirement_set_id END;
  SELECT frozen_at INTO frozen FROM requirement_set WHERE id = set_id;
  IF frozen IS NOT NULL THEN
    RAISE EXCEPTION 'requirement_set % is frozen; requirements are immutable', set_id USING ERRCODE = '55000';
  END IF;
  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END $$;

CREATE TRIGGER requirement_set_frozen_guard
  BEFORE UPDATE OR DELETE ON requirement_set
  FOR EACH ROW EXECUTE FUNCTION forbid_change_when_frozen();

CREATE TRIGGER requirement_frozen_guard
  BEFORE INSERT OR UPDATE OR DELETE ON requirement
  FOR EACH ROW EXECUTE FUNCTION forbid_change_when_frozen();
